FROM openjdk:8
EXPOSE 8080
ADD target/backend-1.0.0.jar backend-1.0.0.jar
ARG APP_NAME="backend"
ARG APP_VERSION="1.0.0"
ARG JAR_FILE="/target/${APP_NAME}-${APP_VERSION}.jar"
ENTRYPOINT ["java","-jar","/backend-1.0.0.jar"]